# Generated by Django 4.1.5 on 2023-01-23 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_status',
            new_name='profile_status',
        ),
    ]
