# Generated by Django 4.1.5 on 2023-01-23 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('profiles', '0002_rename_user_status_profile_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
            preserve_default=False,
        ),
    ]
