# Generated by Django 4.1.5 on 2023-01-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_status',
            field=models.CharField(choices=[('is_owner', 'Owner'), ('is_staff', 'Staff'), ('is_courier', 'Courier')], max_length=10),
        ),
    ]
